# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'MyCloset' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCloset
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Firestore'
  pod 'SnapKit'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'NeumorphismTab'

  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

end
